name: Laravel CI

on:
  push:
    branches: [ main, Merge ]
  pull_request:
    branches: [ main, Merge ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: javaspringboot
          MYSQL_DATABASE: qr_code_ordering_system
        ports:
          - 3308:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql, pdo_mysql

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h"127.0.0.1" -P"3308" --silent; do
            echo 'Waiting for MySQL to be ready...'
            sleep 2
          done

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Remove invalid .env.testing if exists
        run: rm -f .env.testing

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Clear Config Cache
        run: php artisan config:clear

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Execute tests
        run: vendor/bin/phpunit

      - name: Build Docker Image (Test)
        run: docker build -t qr-ordering-api .
